on: [push]

jobs:
  build-paper:
    runs-on: ubuntu-latest
    name: Build JOSS Paper
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: paper.pdf
