on:
  push:
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml

jobs:
  build-paper:
    runs-on: ubuntu-latest
    name: Build JOSS Paper
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build draft PDF
        uses: actions/upload-artifact@3d19d1b2c19308c378efb001623e8f4f015cadcd
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: paper.pdf

      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          # This should be the path to the paper within your repo.
          add: 'paper.pdf' # 'paper/*.pdf' to commit all PDFs in the paper directory
